Feat/ds 482/modal
migrationsverket/midas pull request #108
Opened 2024-10-24 09:01 UTC by jabkha

2024-10-24 11:27 UTC, wilhjelmig reviewed
Se kommentarer :)

2024-10-24 11:27 UTC, wilhjelmig commented on packages/modal/src/lib/Modal.tsx
> +      <Button>Open dialog</Button>
De här är för hårdkodat. Alla som använder komponenten kan inte ha en knapp som säger "Open dialog". Det borde istället vara ett exempel på hur man kan trigga en dialog med vår @midas-ds/button knapp

2024-10-24 11:27 UTC, wilhjelmig commented on packages/modal/src/lib/Modal.tsx
> +import { Button } from '../../../../packages/button/src/lib/Button'
Importen ska vara @midas-ds/button

2024-10-24 11:27 UTC, wilhjelmig commented on packages/modal/src/lib/Modal.module.css
> +  font-family: Inter;
Det här har vi en variabel för. Se övriga komponenter.

2024-10-24 11:27 UTC, wilhjelmig commented on packages/modal/src/lib/Modal.module.css
> +  width: 356px;
Fast höjd/bredd är en no no. Det behöver vara med skalbart.

2024-10-24 11:27 UTC, wilhjelmig commented on packages/modal/src/lib/Modal.module.css
> +  height: 48px;
Inga fasta höjder.

2024-10-24 11:27 UTC, wilhjelmig commented on packages/modal/src/lib/Modal.tsx
> +  ...props
Denna används inte, varför definieras den?

2024-10-24 11:27 UTC, wilhjelmig commented on packages/modal/src/lib/Modal.module.css
> +.buttonContainer {
Denna används inte?

2024-10-28 13:39 UTC, wilhjelmig commented on packages/modal/src/lib/Modal.module.css
> +@keyframes mymodal-slide {
Den här används inte?

2024-10-28 13:39 UTC, wilhjelmig commented on packages/modal/src/lib/Modal.module.css
> +.buttonContainer {
Borde inte inkluderas i komponenten såhär. Används bara i storybook.

2024-10-28 13:39 UTC, wilhjelmig commented on packages/modal/src/lib/Modal.stories.tsx
> +            <Button size="small">Unsubscribe</Button>
Blandar engelska och svenska här

2024-10-31 08:40 UTC, phieksmig requested changes

2024-10-31 08:40 UTC, phieksmig commented on packages/modal/src/lib/Modal.tsx
> +                  size="small"
I underlaget är det en large button så det ska det vara här också! Vet inte hur tydligt det är när man inte har Devmode. Om det är svårt att se får du säga till så ska jag förtydliga det!

2024-10-31 08:40 UTC, phieksmig commented on packages/modal/src/lib/Modal.stories.tsx
> +            <Button size="small">Spara korr.</Button>
Knapparna i underlaget är large

2024-10-31 08:40 UTC, phieksmig commented on packages/modal/src/lib/Modal.module.css
> +  padding: 0.688rem 0.375rem 0.688rem 0;
Pga att du använt small button så blir det jättekonstiga siffror här. Jag använder bara hela pixlar i designen och 0.688 rem ger typ 11.008 px. Med large button så borde det inte behövas eftersom den är 48px / 3 rem hög.

2024-10-31 14:21 UTC, wilhjelmig commented
Already merged in #118

2024-10-31 14:21 UTC, closed without merging