Feat/ds 464/link button
migrationsverket/midas pull request #126
Opened 2024-11-06 08:15 UTC by jabkha

2024-11-06 08:24 UTC, wilhjelmig commented on packages/link-button/src/lib/LinkButton.module.css
> -  width: calc(100% - calc(1.9375rem * 2));
Jag tror vi ska behålla det här. Samt att köra justify-content: space-between;. Philip kan förklara :)

2024-11-06 08:51 UTC, phieksmig requested changes

2024-11-06 08:51 UTC, phieksmig commented on packages/link-button/src/lib/LinkButton.module.css
> +  justify-content: center;
Byt till space-between, annars blir det inte som i underlaget

2024-11-06 08:56 UTC, phieksmig commented
![image](https://github.com/user-attachments/assets/c124cd8c-3e4a-457a-b84f-8644c648ea39)

Cevron och text är inte centrerad, men när man tar bort align-items: center så blir de det. Mycket oklart

2024-11-06 08:57 UTC, phieksmig commented
Hoverbeteendet är inte enligt skiss
![image](https://github.com/user-attachments/assets/cf33b578-e85b-4f8d-88dd-4856f000b361)

2024-11-06 09:03 UTC, phieksmig commented on packages/link-button/src/lib/LinkButton.module.css
> +  padding: 0.875rem 1.688rem 0.875rem 1rem;
Varför är padding right 1,688 rem?

2024-11-06 09:04 UTC, phieksmig commented on packages/link-button/src/lib/LinkButton.module.css
> +  margin: 0.188rem -1rem 0 0;
Negativ marginal! Det kan vi inte ha!

2024-11-06 09:16 UTC, phieksmig requested changes

2024-11-06 09:16 UTC, phieksmig commented on packages/link-button/src/lib/LinkButton.tsx
> +        size={20}
size={16} enligt underlaget! Byt till detta

2024-11-08 10:29 UTC, phieksmig requested changes

2024-11-08 10:29 UTC, phieksmig commented on packages/link/src/lib/Link.module.css
> +.standalone {
Docweb: 

![image](https://github.com/user-attachments/assets/688d8e13-fc8f-4147-ab30-4bf29d05b42c)

Storybook:
![image](https://github.com/user-attachments/assets/25e976ec-993c-4019-8af5-cb5fe0b882bc)


Linjeringen ser ok ut på Storybook men konstigt på Docwebben. 
aign-items: center kanske?

2024-11-08 10:29 UTC, phieksmig commented on packages/link/src/lib/Link.module.css
> +
Saknar :active och :visited, se underlaget

2024-11-08 10:29 UTC, phieksmig commented on packages/link/src/lib/Link.module.css
> +}
Hover mfl på Standalone ska ha text-decoration:underline; . Se underlaget

2024-11-08 12:14 UTC, phieksmig commented
Jag ska jobba vidare på mönstret, så det är ok att det är ofärdigt i denna PR

2024-11-11 10:44 UTC, phieksmig approved these changes

2024-11-11 10:59 UTC, wilhjelmig approved these changes

2024-11-11 10:59 UTC, merged